# Generated by Django 4.2.2 on 2023-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sneakers_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/snicker'),
        ),
    ]
