# Generated by Django 4.2.2 on 2023-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sneakers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/snicker'),
        ),
    ]
