# Generated by Django 4.2.2 on 2023-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sneakers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
