# Generated by Django 4.2.2 on 2023-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sneakers_sneakers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='account-img.png', null=True, upload_to='images/users'),
        ),
    ]
