# Generated by Django 4.2.2 on 2023-06-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
